export const GlobalConstants = {
    // TIPOS
    TIPO_TRANSACCION_INGRESO: 1,
    TIPO_TRANSACCION_GASTO: 2,

    // CLAVES
    KEY_TIPO_TRANSACCION: 'TIPO_TRANSACCION',
    KEY_DEFAULT_CUENTA: 'DEFAULT_CUENTA',
    KEY_DEFAULT_CATEGORIA_INGRESO: 'DEFAULT_CATEGORIA_INGRESO',
    KEY_DEFAULT_CATEGORIA_GASTO: 'DEFAULT_CATEGORIA_GASTO'
}